robot_localization:
  ros__parameters:
    frequency: 30.0
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

     # Odométrie (encodeurs via ESP32)
    odom0: /odom
    odom0_config:
        - true       # x
        - true       # y
        - false      # z
        - false      # roll
        - false      # pitch
        - true       # yaw
        - false      # x vel
        - false      # y vel
        - true       # yaw vel
        - false
        - false
        - false

    process_noise_covariance:
        - 0.05
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.03
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0

    initial_estimate_covariance:
        - 1e-9
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 1e-9
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 1e-9
